sudo: true
dist: trusty
cache: false
language: python
install:
- export URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_65674265f95b_key -iv $encrypted_65674265f95b_iv -in assets/server.key.enc -out assets/server.key -d || true'
- wget -qO- $URL | tar xJf -
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- mv force-app/main/test/* force-app/main/default/classes

script:
- "./install/test-in-scratch-org.sh"
after_success:
- sfdx force:org:delete -u ciorg -p
after_failure:
- sfdx force:org:delete -u ciorg -p

